-- Day 5 seed data: first 20 entities for the Dance of the Dragons dataset
-- Source basis: A Wiki of Ice and Fire, Dance of the Dragons entry
-- UUIDs are generated by PostgreSQL so we do not hardcode IDs.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO entities (id, type, name, valid_from, valid_to, attributes) VALUES
  (gen_random_uuid(), 'house', 'House Targaryen', '0001-01-01', '0131-12-31', '{"house":"House Targaryen","faction":"Targaryen","region":"Westeros","source":"Dance of the Dragons","notes":"The ruling dynasty of the Seven Kingdoms."}'::jsonb),
  (gen_random_uuid(), 'house', 'House Velaryon', '0001-01-01', '0131-12-31', '{"house":"House Velaryon","faction":"Velaryon","region":"Blackwater Bay","source":"Dance of the Dragons","notes":"A powerful noble house with close ties to House Targaryen."}'::jsonb),
  (gen_random_uuid(), 'house', 'House Hightower', '0001-01-01', '0131-12-31', '{"house":"House Hightower","faction":"Green","region":"The Reach","source":"Dance of the Dragons","notes":"A major Reach house aligned with the greens during the war."}'::jsonb),
  (gen_random_uuid(), 'house', 'House Baratheon', '0001-01-01', '0131-12-31', '{"house":"House Baratheon","faction":"Green","region":"Stormlands","source":"Dance of the Dragons","notes":"A key stormland house whose loyalties shifted during the succession crisis."}'::jsonb),
  (gen_random_uuid(), 'house', 'House Arryn', '0001-01-01', '0131-12-31', '{"house":"House Arryn","faction":"Black","region":"The Vale","source":"Dance of the Dragons","notes":"House Arryn was a significant supporter of Rhaenyra''s claim."}'::jsonb),
  (gen_random_uuid(), 'house', 'House Stark', '0001-01-01', '0131-12-31', '{"house":"House Stark","faction":"Black","region":"The North","source":"Dance of the Dragons","notes":"Stark backing mattered in the broader war effort for the blacks."}'::jsonb),
  (gen_random_uuid(), 'person', 'Viserys I Targaryen', '0104-01-01', '0117-01-01', '{"house":"House Targaryen","faction":"Throne","region":"King''s Landing","source":"Dance of the Dragons","notes":"King whose succession dispute triggered the civil war."}'::jsonb),
  (gen_random_uuid(), 'person', 'Aemma Arryn', '0100-01-01', '0105-12-31', '{"house":"House Arryn","faction":"Targaryen","region":"King''s Landing","source":"Dance of the Dragons","notes":"First queen of Viserys I and mother of Rhaenyra."}'::jsonb),
  (gen_random_uuid(), 'person', 'Rhaenyra Targaryen', '0105-01-01', '0130-12-31', '{"house":"House Targaryen","faction":"Black","region":"Dragonstone","source":"Dance of the Dragons","notes":"Heir to Viserys I and central claimant in the war."}'::jsonb),
  (gen_random_uuid(), 'person', 'Alicent Hightower', '0104-01-01', '0131-12-31', '{"house":"House Hightower","faction":"Green","region":"King''s Landing","source":"Dance of the Dragons","notes":"Queen consort to Viserys I and mother of the green claimants."}'::jsonb),
  (gen_random_uuid(), 'person', 'Otto Hightower', '0098-01-01', '0130-12-31', '{"house":"House Hightower","faction":"Green","region":"Oldtown","source":"Dance of the Dragons","notes":"Hand of the King and Alicent''s father, a central political figure in the green faction."}'::jsonb),
  (gen_random_uuid(), 'person', 'Aegon II Targaryen', '0112-01-01', '0130-12-31', '{"house":"House Targaryen","faction":"Green","region":"King''s Landing","source":"Dance of the Dragons","notes":"Son of Viserys I and Alicent; green claimant to the Iron Throne."}'::jsonb),
  (gen_random_uuid(), 'person', 'Daemon Targaryen', '0108-01-01', '0130-12-31', '{"house":"House Targaryen","faction":"Black","region":"Dragonstone","source":"Dance of the Dragons","notes":"Brother to Viserys I and key black political and military figure."}'::jsonb),
  (gen_random_uuid(), 'person', 'Corlys Velaryon', '0107-01-01', '0131-12-31', '{"house":"House Velaryon","faction":"Black","region":"Driftmark","source":"Dance of the Dragons","notes":"The Sea Snake and major supporter of the blacks."}'::jsonb),
  (gen_random_uuid(), 'person', 'Rhaenys Targaryen', '0100-01-01', '0130-12-31', '{"house":"House Targaryen","faction":"Black","region":"Driftmark","source":"Dance of the Dragons","notes":"The queen who never was and a major black supporter."}'::jsonb),
  (gen_random_uuid(), 'person', 'Laenor Velaryon', '0109-01-01', '0120-12-31', '{"house":"House Velaryon","faction":"Black","region":"Driftmark","source":"Dance of the Dragons","notes":"Rhaenyra''s first husband and father of her first sons."}'::jsonb),
  (gen_random_uuid(), 'person', 'Jacaerys Velaryon', '0114-01-01', '0129-12-31', '{"house":"House Velaryon","faction":"Black","region":"Dragonstone","source":"Dance of the Dragons","notes":"Rhaenyra''s eldest son and black heir apparent."}'::jsonb),
  (gen_random_uuid(), 'person', 'Lucerys Velaryon', '0116-01-01', '0129-12-31', '{"house":"House Velaryon","faction":"Black","region":"Dragonstone","source":"Dance of the Dragons","notes":"Rhaenyra''s younger son whose death triggered major escalation."}'::jsonb),
  (gen_random_uuid(), 'person', 'Joffrey Velaryon', '0118-01-01', '0129-12-31', '{"house":"House Velaryon","faction":"Black","region":"Dragonstone","source":"Dance of the Dragons","notes":"Rhaenyra''s youngest son by Laenor and a black prince."}'::jsonb),
  (gen_random_uuid(), 'person', 'Aemond Targaryen', '0112-01-01', '0130-12-31', '{"house":"House Targaryen","faction":"Green","region":"King''s Landing","source":"Dance of the Dragons","notes":"Alicent and Viserys''s son, and one of the war''s most feared dragonriders."}'::jsonb);

-- Attach the core source to every entity in this seed set.
WITH source_row AS (
  INSERT INTO sources (id, title, author, publication_date, source_type, citation, metadata)
  VALUES (
    gen_random_uuid(),
    'Dance of the Dragons',
    'A Wiki of Ice and Fire',
    NULL,
    'wiki',
    'https://awoiaf.westeros.org/index.php/Dance_of_the_Dragons',
    '{"url":"https://awoiaf.westeros.org/index.php/Dance_of_the_Dragons","notes":"Primary reference used for the initial Day 5 dataset and the black/green faction graph."}'::jsonb
  )
  RETURNING id
)
INSERT INTO entity_sources (entity_id, source_id)
SELECT e.id, s.id
FROM entities e
CROSS JOIN source_row s;

-- Notes:
-- This file intentionally seeds the first 20 core entities for the MVP historical graph.
-- Additional entities, sources, and relationships can be added in later iteration steps.
